# Generated by Django 5.0.7 on 2024-07-30 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='trips',
        ),
        migrations.AddField(
            model_name='stop',
            name='dateAndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.trips'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
