# Generated by Django 5.0.7 on 2024-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_location_stop_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
