# Generated by Django 5.0.7 on 2024-08-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_trip_user_delete_userdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='trip',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='catalog.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
