# Generated by Django 5.0.7 on 2024-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_stop_location_alter_stop_trip_alter_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='type_of_stop',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Cafe', 'Cafe'), ('City', 'City'), ('Desert', 'Desert'), ('Eating', 'Eating'), ('Nature', 'Nature'), ('Sight Seeing', 'Sight Seeing'), ('Travel', 'Travel'), ('Other', 'Other')], default='Default', max_length=30),
        ),
    ]
