# Generated by Django 5.0.7 on 2024-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_stop_type_of_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='type_of_stop',
            field=models.CharField(choices=[('Sea', 'Sea'), ('Cafe', 'Cafe'), ('City', 'City'), ('Eating', 'Eating'), ('Nature', 'Nature'), ('Sight Seeing', 'Sight Seeing'), ('Travel', 'Travel'), ('Free Time', 'Free Time'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
