# Generated by Django 5.0.7 on 2024-08-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_stop_type_of_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='type_of_stop',
            field=models.CharField(choices=[('sea', 'sea'), ('cafe', 'cafe'), ('city', 'city'), ('eating', 'eating'), ('nature', 'nature'), ('sightSeeing', 'sightSeeing'), ('travel', 'travel'), ('freeTime', 'freeTime'), ('other', 'other')], default='other', max_length=30),
        ),
    ]
