# Generated by Django 5.0.7 on 2024-08-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_lodging_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='dateAndTime',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='dateAndTime',
        ),
        migrations.AddField(
            model_name='lodging',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lodging',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
