# Generated by Django 5.0.7 on 2024-08-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_stop_dateandtime_remove_transport_dateandtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='time',
            new_name='start_time',
        ),
    ]
