# Generated by Django 5.0.7 on 2024-08-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_rename_date_stop_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='start_time',
            new_name='time',
        ),
    ]
