# Generated by Django 5.0.7 on 2024-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_stop_location_remove_lodging_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
