# Generated by Django 5.0.7 on 2024-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_lodging_note_stop_note_transport_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
