# Generated by Django 5.0.7 on 2024-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_trip_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='formattedAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='location_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
