# Generated by Django 5.0.7 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_lodging_formattedaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='note2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
