# Generated by Django 5.0.7 on 2024-08-28 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('trip', 'invited_user')},
        ),
    ]
