# Generated by Django 5.0.7 on 2024-08-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_invite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileLodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=None)),
                ('type_of_file', models.CharField(choices=[('ticket', 'Ticket'), ('lodging', 'Lodging'), ('reservations', 'Reservations'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.lodging')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=None)),
                ('type_of_file', models.CharField(choices=[('ticket', 'Ticket'), ('lodging', 'Lodging'), ('reservations', 'Reservations'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.stop')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=None)),
                ('type_of_file', models.CharField(choices=[('ticket', 'Ticket'), ('lodging', 'Lodging'), ('reservations', 'Reservations'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalog.transport')),
            ],
        ),
    ]
