# Generated by Django 5.0.7 on 2024-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_uploadfilelodging_uploadfilestop_uploadfiletransport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiletransport',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
