# Generated by Django 5.0.7 on 2024-08-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_uploadfiletransport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilelodging',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadfilestop',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadfiletransport',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
