# Generated by Django 5.0.7 on 2024-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_uploadfilelodging_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilelodging',
            name='type_of_file',
            field=models.CharField(choices=[('lodging_detail', 'Lodging Detail'), ('reservation', 'Reservation'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadfilestop',
            name='type_of_file',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('reservation', 'Reservation'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadfiletransport',
            name='type_of_file',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('reservation', 'Reservation'), ('other_attachment', 'Other Attachment')], default='other_attachment', max_length=30),
        ),
    ]
